name: bruno_bookshop
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - sqlalchemy
  - alembic
  - psycopg2
  - pydantic
  - passlib
  - bcrypt
  - sentence-transformers
  - httpx
  - pytest
  - pip
  - pip:
    - python-jose[cryptography]
    - python-multipart
    - python-dotenv
    - pydantic-settings
    - email-validator
    - pgvector
