import sys
import os

# Ensure src is on path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))

from decimal import Decimal
from sqlalchemy.orm import Session
from src.database import SessionLocal, engine
from src import models
from src.services.ai_service import generate_book_embedding

# Sample books data
BOOKS = [
    {
        "title": "Things Fall Apart",
        "author": "Chinua Achebe",
        "genre": "Fiction",
        "description": "A classic of modern African literature, depicting pre-colonial life in Nigeria and the arrival of Europeans.",
        "isbn": "9780385474542",
        "publisher": "Anchor Books",
        "price": Decimal("12.99"),
        "stock_count": 50,
        "average_rating": Decimal("4.50"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780385474542-L.jpg",
    },
    {
        "title": "1984",
        "author": "George Orwell",
        "genre": "Fiction",
        "description": "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism.",
        "isbn": "9780451524935",
        "publisher": "Signet Classic",
        "price": Decimal("10.99"),
        "stock_count": 80,
        "average_rating": Decimal("4.70"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    },
    {
        "title": "Sapiens: A Brief History of Humankind",
        "author": "Yuval Noah Harari",
        "genre": "History",
        "description": "Explores how biology and history have defined us and enhanced our understanding of what it means to be human.",
        "isbn": "9780062316097",
        "publisher": "Harper",
        "price": Decimal("18.99"),
        "stock_count": 40,
        "average_rating": Decimal("4.60"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
    },
    {
        "title": "Clean Code: A Handbook of Agile Software Craftsmanship",
        "author": "Robert C. Martin",
        "genre": "Technology",
        "description": "Even bad code can function. But if code isn't clean, it can bring a development organization to its knees.",
        "isbn": "9780132350884",
        "publisher": "Prentice Hall",
        "price": Decimal("42.99"),
        "stock_count": 25,
        "average_rating": Decimal("4.40"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg",
    },
    {
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "genre": "Fiction",
        "description": "A novel about the serious issues of rape and racial inequality, told through the eyes of young Scout Finch.",
        "isbn": "9780061120084",
        "publisher": "Harper Perennial",
        "price": Decimal("14.99"),
        "stock_count": 60,
        "average_rating": Decimal("4.80"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg",
    },
    {
        "title": "The Lean Startup",
        "author": "Eric Ries",
        "genre": "Business",
        "description": "How today's entrepreneurs use continuous innovation to create radically successful businesses.",
        "isbn": "9780307887894",
        "publisher": "Crown Business",
        "price": Decimal("16.99"),
        "stock_count": 35,
        "average_rating": Decimal("4.30"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg",
    },
    {
        "title": "Becoming",
        "author": "Michelle Obama",
        "genre": "Biography",
        "description": "The intimate, powerful, and inspiring memoir by the former First Lady of the United States.",
        "isbn": "9781524763138",
        "publisher": "Crown",
        "price": Decimal("19.99"),
        "stock_count": 45,
        "average_rating": Decimal("4.70"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9781524763138-L.jpg",
    },
    {
        "title": "A Brief History of Time",
        "author": "Stephen Hawking",
        "genre": "Science",
        "description": "Explores profound questions about the universe, from the Big Bang to black holes, in accessible language.",
        "isbn": "9780553380163",
        "publisher": "Bantam",
        "price": Decimal("15.99"),
        "stock_count": 30,
        "average_rating": Decimal("4.50"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg",
    },
    {
        "title": "The Alchemist",
        "author": "Paulo Coelho",
        "genre": "Fiction",
        "description": "A magical story about Santiago, an Andalusian shepherd boy who yearns to travel in search of treasure.",
        "isbn": "9780061122415",
        "publisher": "HarperOne",
        "price": Decimal("13.99"),
        "stock_count": 70,
        "average_rating": Decimal("4.20"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780061122415-L.jpg",
    },
    {
        "title": "Introduction to Algorithms",
        "author": "Thomas H. Cormen et al.",
        "genre": "Technology",
        "description": "The standard reference for algorithms, widely used as a textbook in universities worldwide.",
        "isbn": "9780262033848",
        "publisher": "MIT Press",
        "price": Decimal("85.00"),
        "stock_count": 15,
        "average_rating": Decimal("4.60"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780262033848-L.jpg",
    },
    {
        "title": "Thinking, Fast and Slow",
        "author": "Daniel Kahneman",
        "genre": "Psychology",
        "description": "A groundbreaking tour of the mind, explaining the two systems that drive the way we think.",
        "isbn": "9780374533557",
        "publisher": "Farrar, Straus and Giroux",
        "price": Decimal("17.99"),
        "stock_count": 40,
        "average_rating": Decimal("4.40"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg",
    },
    {
        "title": "Educated",
        "author": "Tara Westover",
        "genre": "Biography",
        "description": "A memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD.",
        "isbn": "9780399590504",
        "publisher": "Random House",
        "price": Decimal("16.99"),
        "stock_count": 55,
        "average_rating": Decimal("4.60"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg",
    },
    {
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "genre": "Fiction",
        "description": "A portrait of the Jazz Age in all its decadence and excess, captured through the story of Jay Gatsby.",
        "isbn": "9780743273565",
        "publisher": "Scribner",
        "price": Decimal("11.99"),
        "stock_count": 65,
        "average_rating": Decimal("4.30"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
    },
    {
        "title": "Python Crash Course",
        "author": "Eric Matthes",
        "genre": "Technology",
        "description": "A hands-on, project-based introduction to programming with Python, perfect for beginners.",
        "isbn": "9781593279288",
        "publisher": "No Starch Press",
        "price": Decimal("29.99"),
        "stock_count": 40,
        "average_rating": Decimal("4.70"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9781593279288-L.jpg",
    },
    {
        "title": "Atomic Habits",
        "author": "James Clear",
        "genre": "Self-Help",
        "description": "An easy and proven way to build good habits and break bad ones, transforming your life incrementally.",
        "isbn": "9780735211292",
        "publisher": "Avery",
        "price": Decimal("19.99"),
        "stock_count": 90,
        "average_rating": Decimal("4.80"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
    },
    {
        "title": "The Art of War",
        "author": "Sun Tzu",
        "genre": "Philosophy",
        "description": "An ancient Chinese military treatise dating from the Late Spring and Autumn Period, still relevant today.",
        "isbn": "9781599869773",
        "publisher": "Filiquarian",
        "price": Decimal("8.99"),
        "stock_count": 100,
        "average_rating": Decimal("4.20"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9781599869773-L.jpg",
    },
    {
        "title": "Rich Dad Poor Dad",
        "author": "Robert T. Kiyosaki",
        "genre": "Business",
        "description": "What the rich teach their kids about money that the poor and middle class do not.",
        "isbn": "9781612680194",
        "publisher": "Plata Publishing",
        "price": Decimal("14.99"),
        "stock_count": 75,
        "average_rating": Decimal("4.30"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg",
    },
    {
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "genre": "Fiction",
        "description": "A romantic novel of manners that portrays the British Regency era through the Bennet family.",
        "isbn": "9780141439518",
        "publisher": "Penguin Classics",
        "price": Decimal("9.99"),
        "stock_count": 85,
        "average_rating": Decimal("4.60"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
    },
    {
        "title": "Deep Learning",
        "author": "Ian Goodfellow, Yoshua Bengio, Aaron Courville",
        "genre": "Technology",
        "description": "An introduction to a broad range of topics in deep learning, offering mathematical and conceptual background.",
        "isbn": "9780262035613",
        "publisher": "MIT Press",
        "price": Decimal("72.00"),
        "stock_count": 20,
        "average_rating": Decimal("4.50"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780262035613-L.jpg",
    },
    {
        "title": "The Catcher in the Rye",
        "author": "J.D. Salinger",
        "genre": "Fiction",
        "description": "A story about teenage angst and alienation, following Holden Caulfield in New York City.",
        "isbn": "9780316769488",
        "publisher": "Little, Brown and Company",
        "price": Decimal("12.99"),
        "stock_count": 60,
        "average_rating": Decimal("4.10"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg",
    },
    {
        "title": "Guns, Germs, and Steel",
        "author": "Jared Diamond",
        "genre": "History",
        "description": "A transdisciplinary non-fiction book that explores why Eurasian civilizations survived and conquered others.",
        "isbn": "9780393317558",
        "publisher": "W. W. Norton & Company",
        "price": Decimal("17.99"),
        "stock_count": 35,
        "average_rating": Decimal("4.40"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780393317558-L.jpg",
    },
    {
        "title": "The Selfish Gene",
        "author": "Richard Dawkins",
        "genre": "Science",
        "description": "A book on evolution that popularized the gene-centered view of evolution and introduced the term meme.",
        "isbn": "9780199291151",
        "publisher": "Oxford University Press",
        "price": Decimal("15.99"),
        "stock_count": 30,
        "average_rating": Decimal("4.50"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780199291151-L.jpg",
    },
    {
        "title": "Zero to One",
        "author": "Peter Thiel",
        "genre": "Business",
        "description": "Notes on startups, or how to build the future by creating something new instead of competing.",
        "isbn": "9780804139298",
        "publisher": "Crown Business",
        "price": Decimal("18.99"),
        "stock_count": 45,
        "average_rating": Decimal("4.30"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780804139298-L.jpg",
    },
    {
        "title": "Meditations",
        "author": "Marcus Aurelius",
        "genre": "Philosophy",
        "description": "A series of personal writings by Marcus Aurelius, Roman Emperor, recording his private notes to himself.",
        "isbn": "9780140449334",
        "publisher": "Penguin Classics",
        "price": Decimal("10.99"),
        "stock_count": 50,
        "average_rating": Decimal("4.70"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780140449334-L.jpg",
    },
    {
        "title": "The Hobbit",
        "author": "J.R.R. Tolkien",
        "genre": "Fantasy",
        "description": "A fantasy novel following the quest of home-loving Bilbo Baggins to win a share of the treasure guarded by Smaug.",
        "isbn": "9780547928227",
        "publisher": "Mariner Books",
        "price": Decimal("13.99"),
        "stock_count": 70,
        "average_rating": Decimal("4.80"),
        "cover_image_url": "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
    },
]


def seed():
    db: Session = SessionLocal()
    try:
        existing = db.query(models.Book).count()
        if existing > 0:
            print(f"Database already has {existing} books. Skipping seed to avoid duplicates.")
            return

        print("Seeding books...")
        for data in BOOKS:
            book = models.Book(**data)
            db.add(book)
            db.commit()
            db.refresh(book)
            generate_book_embedding(book, db)
            print(f"  Added: {book.title}")

        print(f"Successfully seeded {len(BOOKS)} books.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
